services:
  timecapsule-mount:
    build:
      context: .
    container_name: timecapsule-mount
    env_file:
      - .env
    environment:
      AFP_HOST: ${AFP_HOST}
      AFP_USER: ${AFP_USER}
      AFP_PASS: ${AFP_PASS}
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"

