services:
  timecapsule-mount:
    build:
      context: .
    container_name: timecapsule-mount
    env_file:
      - .env
    environment:
      AFP_HOST: ${AFP_HOST}
      USER: ${TM_USER}
      PASS: ${TM_PASS}
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - timemachine-data:/mnt/timecapsule
    restart: unless-stopped

  timemachine:
    image: mbentley/timemachine:smb
    container_name: timecapsule-smb
    hostname: timemachine
    depends_on:
      - timecapsule-mount
    restart: unless-stopped
    network_mode: host
    environment:
      - TM_USERNAME=${TM_USER}
      - PASSWORD=${TM_PASS}
      - SET_PERMISSIONS=false
      - VOLUME_SIZE_LIMIT=0
      - cache-entries-max=0
    volumes:
      - timemachine-data:/opt/timemachine

volumes:
  timemachine-data: