services:
  timecapsule-mount:
    build:
      context: .
    container_name: timecapsule-mount
    env_file:
      - .env
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /run/samba
    restart: unless-stopped
    network_mode: host
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/avahi-daemon/socket:/run/avahi-daemon/socket
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
